### PR TITLE
Add OctoApp support

### PR DESCRIPTION
**Pull request by crysxd**
Accompanying PR for https://github.com/Guilouz/Creality-Helper-Script/pull/3

I had some trouble building the Jekyll side locally due to an error in the Mobileraker section...so I'm not 100% everything looks like it should

### CODE REVIEW

**Comment by Guilouz** [comment]
What do you mean by "I had some trouble building the Jekyll side locally due to an error in the Mobileraker section...so I'm not 100% everything looks like it should" ?

**Comment by crysxd** [comment]
The Jekyll build failed for me with `Liquid Exception: Liquid syntax error (line 131): Unknown tag 'set' in helper-script/mobileraker-companion.md`, but as it worked for you it must be something with my fork. Never mind!

Thank you for merging this so quickly!

**Comment by Guilouz** [comment]
@crysxd Oh ok. I have improved it: https://guilouz.github.io/Creality-K1-Series/helper-script/octoapp-companion/

**Comment by crysxd** [comment]
Thank you!!

**Pull request merged**
